# Generated by Django 4.1 on 2022-09-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('company', models.CharField(max_length=100)),
                ('fuel', models.CharField(max_length=100)),
            ],
        ),
    ]
